apiVersion: v1
kind: ConfigMap
metadata:
  name: #{name}#-configmap
  namespace: #{namespace}#
  labels:
    app.kubernetes.io/name: #{name}#
    app.kubernetes.io/instance: #{name}#-v1.0
    app.kubernetes.io/version: v1.0
    app.kubernetes.io/part-of: #{name}#
data:
  SERVER_PORT: "#{service-port}#"
  APPLICATION_NAME: #{application-name}#
  SPRING_PROFILE_ACTIVE:  #{spring-profile-active}#
  LOG4J_LEVEL:  #{log-level}#
  CACHE_SECRETS_SIZE: "#{cache-secrets-size}#"
  CACHE_SECRETS_SECONDS: "#{cache-secrets-seconds}#"
  PATH_BASE: "#{prefix}#/#{service}#"
  REGION_AWS: #{region-aws}#
  SQS_URL: #{sqs-url}#
  SQS_TIMEOUT: "#{sqs-timeout}#"
  SQS_POOL_SIZE: "#{sqs-pool-size}#"
  SECRET-RABBIT: "#{secret-rabbit}#"
  CACHE: #{cache-host}#
  CACHE_PORT: "#{cache-port}#"
  EXPIRE_TIME_CACHE: "#{cache-time}#"
  S3-BUCKET: #{s3-bucket}#
  NAME-SECRET-BUCKET-SSL: #{secret-bucket}#
  TABLE_NAME_SECRET_PRIORITY: #{table-name-secret-priority}#
  ENDPOINT_INALAMBRIA_SMS: #{endpoint-inalambria-sms}#
  ENDPOINT_INALAMBRIA_TOKEN: #{endpoint-inalambria-token}#