server:
  port: "${SERVER_PORT}"
  servlet:
    encoding:
      charset: "UTF-8"
      force: true
springdoc:
  version: 1
spring:
  application:
    name: "${APPLICATION_NAME}"
  devtools:
    add-properties: false
  jackson:
    default-property-inclusion: "NON_NULL"
  profiles:
    active: "${SPRING_PROFILE_ACTIVE}"
  webflux:
    base-path: "${PATH_BASE}"
  logging:
    level:
      root: "${LOG4J_LEVEL}"
      reactor:
        netty: false
adapters:
  secrets-manager:
    secret-rds: "${SECRET-RDS}"
    cache-size: "${CACHE_SECRETS_SIZE}"
    cache-time: "${CACHE_SECRETS_SECONDS}"
    endpoint: "http://localhost:4566"
  entries:
    reactive-web:
      path-base: "${PATH_BASE}"
      contact: "${CONTACT}"
      client: "${CLIENT}"
  rest-consumer:
    timeout: 1000
    resources:
      basicKit: ${BASIC_KIT:localhost:8081/api/v1/sending-management/alert-client/basic-kit}

cloud:
  aws:
    rds:
      postgresql:
        pool:
          initial: ${POSTGRESQL-POOL-INITIAL}
          max: ${POSTGRESQL-POOL-MAX}
        schema: ${POSTGRESQL-SCHEMA}

management:
  health:
    probes:
      enabled: true
  endpoint:
    health:
      show-details: "never"
      enabled: true
      cache:
        time-to-live: "10s"
  endpoints:
    web:
      exposure:
        include: "health, liveness, readiness"
      base-path: "/"
      path-mapping:
        health: "health"
        liveness: "liveness"
        readiness: "readiness"

