apiVersion: v1
kind: ConfigMap
metadata:
  name: #{name}#-configmap
  namespace: #{namespace}#
  labels:
    app.kubernetes.io/name: #{name}#
    app.kubernetes.io/instance: #{name}#-v1.0
    app.kubernetes.io/version: v1.0
    app.kubernetes.io/part-of: #{name}#
data:
  SERVER_PORT: "#{service-port}#"
  APPLICATION_NAME: #{application-name}#
  SPRING_PROFILE_ACTIVE: #{spring-profile-active}#
  LOG4J_LEVEL: #{log-level}#
  CACHE_SECRETS_SIZE: "#{cache-secrets-size}#"
  CACHE_SECRETS_SECONDS: "#{cache-secrets-seconds}#"
  PATH_BASE: "#{prefix}#/#{service}#"
  REGION_AWS: #{region-aws}#
  SECRET-RABBIT: "#{secret-rabbit}#"
  SECRET_RABBIT_DUAL: #{secret-rabbit-dual}#
  CACHE: #{cache-host}#
  CACHE_PORT: "#{cache-port}#"
  EXPIRE_TIME_CACHE: "#{cache-time}#"
  S3-BUCKET: #{s3-bucket}#
  S3-ATTACHMENT-BUCKET: #{s3-attachment-bucket}#
  S3-SIGNATURE-DURATION-MINS: "#{s3-signature-duration-minutes}#"
  NAME-SECRET-BUCKET-SSL: #{secret-bucket}#
  TABLE_NAME_SECRET_PRIORITY: #{table-name-secret-priority}#
  TABLE_NAME_TEMPLATE_EMAIL: #{table-name-template-email}#
  WAIT-TIME-SECONDS: "#{wait-time-seconds}#"
  MAX-NUMBER-MESSAGES: "#{max-number-messages}#"
  THREADS: "#{threads}#"
  QUEUE-URL: "#{queue-url}#"
  ENDPOINT-SQS: "#{endpoint-sqs}#"
  ENDPOINT_TEMPLATE: "#{endpoint-template}#"





