server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
springdoc:
  version: 1
spring:
  application:
    name: ms_functional_adapter
  freemarker:
    checkTemplateLocation: false
  devtools:
    add-properties: false
  webflux:
    base-path: /api/v1/functional-adapter
  jackson:
    default-property-inclusion: NON_NULL
  logging:
    level:
      root: INFO
      reactor:
        netty: false

app:
  localPath: /dmellizo
  async:
    withDLQRetry: true
    retryDelay: 1000
    maxRetries: 0

aws:
  region: us-east-1
  s3:
    endpoint: http://localhost:4566
    bucket: bucketssl
    request-config-mq-key: nu0154001_config_resource_mq.json
    config-listener-mq-key: nu0154001_config_listener_mq_local.json
  secrets-manager:
    secret-rabbit: alertas-local-secretrabbit-CNX
    cache-size: 300
    cache-time: 2
    endpoint: http://localhost:4566

management:
  endpoints:
    web:
      exposure:
        include: health, liveness, readiness
      base-path: /
      path-mapping:
        health: health
        liveness: liveness
        readiness: readiness
  endpoint:
    health:
      show-details: never