server:
  port: ${SERVER_PORT}
  servlet:
    encoding:
      charset: UTF-8
      force: true
springdoc:
  version: 1
spring:
  application:
    name: ${APPLICATION_NAME}
  devtools:
    add-properties: false
  jackson:
    default-property-inclusion: NON_NULL
  profiles:
    active: ${SPRING_PROFILE_ACTIVE}
  logging:
    level:
      root: ${LOG4J_LEVEL}
      reactor:
        netty: false

app:
  localPath: ${APP_PATH}
  async:
    withDLQRetry: false
    retryDelay: 1000
    maxRetries: 0

aws:
  region: ${AWS-REGION}
  s3:
    endpoint: http://localhost:4566
    bucket: ${S3-BUCKET}
    request-config-mq-key: ${REQUEST-CONFIG-MQ-KEY}
    config-listener-mq-key: ${CONFIG-LISTENER-MQ-KEY}
  secrets-manager:
    secret-rabbit: ${SECRET_RABBIT}
    cache-size: ${CACHE_SECRETS_SIZE}
    cache-time: ${CACHE_SECRETS_SECONDS}
    endpoint: http://localhost:4566
