apiVersion: v1
kind: ConfigMap
metadata:
  name: #{name}#-configmap
  namespace: #{namespace}#
  labels:
    app.kubernetes.io/name: #{name}#
    app.kubernetes.io/instance: #{name}#-v1.0
    app.kubernetes.io/version: v1.0
    app.kubernetes.io/part-of: #{name}#
data:
  SERVER_PORT: "#{service-port}#"
  APPLICATION_NAME: #{application-name}#
  SPRING_PROFILE_ACTIVE:  #{spring-profile-active}#
  LOG4J_LEVEL:  #{log-level}#
  CACHE_SECRETS_SIZE: "#{cache-secrets-size}#"
  CACHE_SECRETS_SECONDS: "#{cache-secrets-seconds}#"
  SECRET-RDS: #{secret-rds}#
  HOST_RDS_READ: #{host-rds-read}#
  PATH_BASE: "#{prefix}#/#{service}#"
  CONTACT: "#{contact}#"
  CLIENT: "#{client}#"
  POSTGRESQL_SCHEMA: #{postgresql-schema}#
  POSTGRESQL_POOL_INITIAL: "#{postgresql-pool-initial}#"
  POSTGRESQL_POOL_MAX: "#{postgresql-pool-max}#"
  SECRET-RABBIT: #{secret-rabbit}#
  RETRIEVE: #{api-retrieve-iseries}#
  SECRET-RETRIEVE: #{secret-retrieve}#
  CHANGEIT: #{changeit}#
  SEND_ALERT_URL: "#{send-alert-url}#"
  SYNCHRONIZE_ISIRIES: "#{synchronize-iseries}#"


