apiVersion: v1
kind: ConfigMap
metadata:
  name: #{name}#-configmap
  namespace: #{namespace}#
  labels:
    app.kubernetes.io/name: #{name}#
    app.kubernetes.io/instance: #{name}#-v1.0
    app.kubernetes.io/version: v1.0
    app.kubernetes.io/part-of: #{name}#
data:
  SERVER_PORT: "#{service-port}#"
  APPLICATION_NAME: #{application-name}#
  SPRING_PROFILE_ACTIVE:  #{spring-profile-active}#
  LOG4J_LEVEL:  #{log-level}#
  PATH_FIND_LOG: "#{path-find-log}#"
  POSTGRESQL_POOL_INITIAL: "#{postgresql-pool-initial}#"
  POSTGRESQL_POOL_MAX: "#{postgresql-pool-max}#"
  POSTGRESQL_SCHEMA: "#{postgresql-schema}#"
  HOST_RDS_READ: "#{host-rds-read}#"
  SECRET_RABBIT: "#{secret-rabbit}#"
  SECRET_RDS: "#{secret-rds}#"
  PATH_BASE: "#{prefix}#/#{service}#"
  DAYS_HOT_DATA: "#{days-hot-data}#"
  JOB_NAME_FIND_LOG: "#{job-name-find-log}#"




