apiVersion: v1
kind: ConfigMap
metadata:
  name: #{name}#-configmap
  namespace: #{namespace}#
  labels:
    app.kubernetes.io/name: #{name}#
    app.kubernetes.io/instance: #{name}#-v1.0
    app.kubernetes.io/version: v1.0
    app.kubernetes.io/part-of: #{name}#
data:
  SERVER_PORT: "#{service-port}#"
  APPLICATION_NAME: #{application-name}#
  SPRING_PROFILE_ACTIVE:  #{spring-profile-active}#
  LOG4J_LEVEL:  #{log-level}#
  SQS-ENDPOINT: #{log-url}#
  SQS_TIMEOUT: "#{log-tmo}#"
  SQS_POOL_SIZE: "#{sqs-pool-size}#"
  REGION_AWS: #{aws-region}#
  POSTGRESQL_SCHEMA: #{postgresql-schema}#
  POSTGRESQL_POOL_INITIAL: "#{postgresql-pool-initial}#"
  POSTGRESQL_POOL_MAX: "#{postgresql-pool-max}#"
  SECRET_RDS: #{secret-rds}#
  PATH_BASE: "#{prefix}#/#{service}#"




