apiVersion: v1
kind: ConfigMap
metadata:
  name: #{name}#-configmap
  namespace: #{namespace}#
  labels:
    app.kubernetes.io/name: #{name}#
    app.kubernetes.io/instance: #{name}#-v1.0
    app.kubernetes.io/version: v1.0
    app.kubernetes.io/part-of: #{name}#
data:
  SERVER_PORT: "#{service-port}#"
  APPLICATION_NAME: #{application-name}#
  SPRING_PROFILE_ACTIVE: #{spring-profile-active}#
  LOG4J_LEVEL: #{log-level}#
  PATH_BASE: "#{prefix}#/#{service}#"
  PATH_CREATE-TEMPLATE: "#{create-template}#"
  PATH_GET-TEMPLATE: "#{get-template}#"
  PATH_PUT-TEMPLATE: "#{put-template}#"
  PATH_DELETE-TEMPLATE: "#{delete-template}#"
  PATH_CREATE-MESSAGE: "#{create-message}#"