##Spring Configuration
server:
  port: ${SERVER_PORT}
spring:
  application:
    name: ${APPLICATION_NAME}
  devtools:
    add-properties: false
  jackson:
    default-property-inclusion: NON_NULL
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:local}
  logging:
    level:
      root: ${LOG4J_LEVEL}
      reactor:
        netty: false

springdoc:
  version: 1

cloud:
  aws:
    region: us-east-1
    stack:
      auto: false
    rds:
      postgresql:
        pool:
          initial: ${POSTGRESQL_POOL_INITIAL:10}
          max: ${POSTGRESQL_POOL_MAX:10}
        schema: ${POSTGRESQL_SCHEMA}
    secrets-manager:
      secret-rds: ${SECRET_RDS}
      endpoint: http://localhost:4566

management:
  endpoints:
    web:
      exposure:
        include: health, liveness, readiness
      base-path: ${PATH_BASE}
      path-mapping:
        health: health
        liveness: liveness
        readiness: readiness
  endpoint:
    health:
      show-details: never