##Spring Configuration
server:
  port: ${SERVER_PORT}
spring:
  application:
    name: ${APPLICATION_NAME}
  devtools:
    add-properties: false
  jackson:
    default-property-inclusion: NON_NULL
  webflux:
    base-path: ${PATH_BASE}
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:local}
  logging:
    level:
      root: ${LOG4J_LEVEL}
      reactor:
        netty: false

springdoc:
  version: 1

adapters:
  entries:
    reactive-web:
      log: ${PATH_FIND_LOG}

cloud:
  aws:
    region: us-east-1
    stack:
      auto: false
    rds:
      postgresql:
        pool:
          initial: ${POSTGRESQL_POOL_INITIAL:10}
          max: ${POSTGRESQL_POOL_MAX:10}
        schema: ${POSTGRESQL_SCHEMA}
        hostRead: ${HOST_RDS_READ}
    secrets-manager:
      secret-rds: ${SECRET_RDS}
      secret-rabbit:  ${SECRET_RABBIT}
      endpoint: http://localhost:4566

management:
  endpoints:
    web:
      exposure:
        include: health, liveness, readiness
      base-path: /
      path-mapping:
        health: health
        liveness: liveness
        readiness: readiness
  endpoint:
    health:
      show-details: never

app.async.withDLQRetry: true
app.async.retryDelay: 1000
app.async.maxRetries: 1