##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: ms_management_log
  devtools:
    add-properties: false
  jackson:
    default-property-inclusion: NON_NULL
  logging:
    level:
      root: INFO
      reactor:
        netty: false

springdoc:
  version: 1

cloud:
  aws:
    region: us-east-1
    stack:
      auto: false
    sqs:
      url: http://localhost:4566/000000000000/logs-alert
      timeout: 300
      pool-size: 2
      region-aws: us-east-1
    rds:
      postgresql:
        pool:
          initial: 10
          max: 10
        schema: schalerd
    secrets-manager:
      secret-rds: alertas-local-secretrds-CNX
      secret-rabbit: alertas-local-secretrabbit-CNX
      endpoint: http://localhost:4566

management:
  endpoints:
    web:
      exposure:
        include: health, liveness, readiness
      base-path: /api/v1/log-management
      path-mapping:
        health: health
        liveness: liveness
        readiness: readiness
  endpoint:
    health:
      show-details: never