name: $(Build.SourceBranchName).$(date:yyyyMMdd)$(rev:.r)

jobs:
  - job: build
    pool:
      name: Build
      demands: agent.os -equals linux

    steps:
      - task: ArchiveFiles@2
        displayName: 'Comprimir Ruta'
        inputs:
          rootFolderOrFile: .
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
      
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Scripts_ETL'
        inputs:
          PathtoPublish: 'etl/scripts_etl/scripts'
          ArtifactName: 'Scripts_ETL'
      
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Acceptance Test'
        inputs:
          PathtoPublish: 'etl/scripts_etl/test/acceptance-test'
          ArtifactName: AcceptanceTest
        
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Acceptance Test log'
        inputs:
          PathtoPublish: 'etl/scripts_etl/test-logs/acceptance-test'
          ArtifactName: AcceptanceTestLogs

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Acceptance Test log sql'
        inputs:
          PathtoPublish: 'ms_log_management/deployment/sql_acceptance_test'
          ArtifactName: AcceptanceTestLogsSQL
